apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
data:
  {{- range .Values.features }}
  {{- if .enabled }}
  {{ .name }}: enabled
  {{- else }}
  {{ .name }}: disabled
  {{- end }}
  {{- end }}

#test12342456735353535353535353
