apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-features
data:
  {{- range .Values.features }}
  {{- if .enabled }}
  {{ .name }}: enabled
  {{- else }}
  {{ .name }}: disabled
  {{- end }}
  {{- end }}

#test
